name: Flutter CI
on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["feature/mvp-activity-locker"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Pub get
        run: |
          cd mobile
          flutter pub get
      - name: Analyze
        run: |
          cd mobile
          flutter analyze
      - name: Test
        run: |
          cd mobile
          flutter test
